
[meta]
version = "1.0.0"
last_scan = "2025-06-19T06:29:20.233Z"
library_count = 1
docs_found = 1
extraction_enabled = false

[libraries.effect]
name = "effect"
version = "3.16.7"
domain = "effect.website"
registry = "npm"
docs_file = "docs/effect/README.md"
fetch_status = "success"
capabilities = []
extraction_confidence = "none"
homepage = "https://effect.website"
llms_txt_url = "https://effect.website/llms.txt"
last_fetched = "2025-06-19T06:29:20.233Z"

[mappings]
